// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250921231115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2110),
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2372)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2618),
                            Name = "Clothing",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2618)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2635),
                            Name = "Books",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2636)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2639),
                            Name = "Home & Kitchen",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2639)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2642),
                            Name = "Sports & Outdoors",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2642)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2660),
                            Name = "Beauty & Health",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2662),
                            Name = "Toys & Games",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2663)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2698),
                            Name = "Automotive",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2698)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2701),
                            Name = "Pet Supplies",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2701)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2703),
                            Name = "Office & Stationery",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(2703)
                        });
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6f2ad3b-3ec3-4c46-9343-5b4b76f2c8a3"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 201, DateTimeKind.Utc).AddTicks(1066),
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 201, DateTimeKind.Utc).AddTicks(1067)
                        },
                        new
                        {
                            Id = new Guid("92f01cf2-650c-41c6-9137-20845d7d56b7"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 201, DateTimeKind.Utc).AddTicks(1076),
                            Name = "Seller",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 201, DateTimeKind.Utc).AddTicks(1076)
                        },
                        new
                        {
                            Id = new Guid("d31fb846-64d2-49fb-a8a0-02c39502ff21"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 201, DateTimeKind.Utc).AddTicks(1078),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 201, DateTimeKind.Utc).AddTicks(1079)
                        });
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9859),
                            Name = "New",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9860)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9870),
                            Name = "Sale",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9870)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa3-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9872),
                            Name = "Popular",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9873)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa4-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9875),
                            Name = "Limited Edition",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9875)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa5-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9877),
                            Name = "Free Shipping",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9877)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa6-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9879),
                            Name = "Eco-Friendly",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9880)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa7-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9882),
                            Name = "Handmade",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9882)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa8-aaaa-aaaa-aaaa-aaaaaaaaaaa8"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9884),
                            Name = "Best Seller",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9884)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa9-aaaa-aaaa-aaaa-aaaaaaaaaaa9"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9891),
                            Name = "On Discount",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9892)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa10-aaaa-aaaa-aaaa-aaaaaaaaaaa0"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9894),
                            Name = "Limited Stock",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9894)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa11-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9896),
                            Name = "Trending",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9897)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa12-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9899),
                            Name = "Gift",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9899)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa13-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9901),
                            Name = "Seasonal",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9902)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa14-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9904),
                            Name = "Exclusive",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9904)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa15-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9906),
                            Name = "Bundle",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9906)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa16-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9908),
                            Name = "Limited Time Offer",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9909)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa17-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9913),
                            Name = "Preorder",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9913)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa18-aaaa-aaaa-aaaa-aaaaaaaaaaa8"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9916),
                            Name = "Popular Choice",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9917)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa19-aaaa-aaaa-aaaa-aaaaaaaaaaa9"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9927),
                            Name = "Hot Deal",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9928)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa20-aaaa-aaaa-aaaa-aaaaaaaaaaa0"),
                            CreatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9930),
                            Name = "Back in Stock",
                            UpdatedAt = new DateTime(2025, 9, 21, 23, 11, 13, 200, DateTimeKind.Utc).AddTicks(9930)
                        });
                });

            modelBuilder.Entity("MyShop.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("MyShop.Domain.ListLikeEntities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("MyShop.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MyShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShop.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("MyShop.Domain.ListLikeEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.ProductTag", b =>
                {
                    b.HasOne("MyShop.Domain.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShop.Domain.ListLikeEntities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
