// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShop.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyShop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyShop.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7247),
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7503)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7746),
                            Name = "Clothing",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7746)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7750),
                            Name = "Books",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7750)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7753),
                            Name = "Home & Kitchen",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7754)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7756),
                            Name = "Sports & Outdoors",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7756)
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7760),
                            Name = "Beauty & Health",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7760)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7775),
                            Name = "Toys & Games",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7775)
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7777),
                            Name = "Automotive",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7778)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7780),
                            Name = "Pet Supplies",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7781)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7783),
                            Name = "Office & Stationery",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 59, DateTimeKind.Utc).AddTicks(7783)
                        });
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4590),
                            Name = "New",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4591)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4602),
                            Name = "Sale",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4602)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa3-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4605),
                            Name = "Popular",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4636)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa4-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4640),
                            Name = "Limited Edition",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4640)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa5-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4663),
                            Name = "Free Shipping",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4663)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa6-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4665),
                            Name = "Eco-Friendly",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4666)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa7-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4669),
                            Name = "Handmade",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4669)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa8-aaaa-aaaa-aaaa-aaaaaaaaaaa8"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4671),
                            Name = "Best Seller",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4672)
                        },
                        new
                        {
                            Id = new Guid("aaaaaaa9-aaaa-aaaa-aaaa-aaaaaaaaaaa9"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4674),
                            Name = "On Discount",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4675)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa10-aaaa-aaaa-aaaa-aaaaaaaaaaa0"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4678),
                            Name = "Limited Stock",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4678)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa11-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4680),
                            Name = "Trending",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4681)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa12-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4683),
                            Name = "Gift",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4684)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa13-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4688),
                            Name = "Seasonal",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4688)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa14-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4691),
                            Name = "Exclusive",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4691)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa15-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4694),
                            Name = "Bundle",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4694)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa16-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4696),
                            Name = "Limited Time Offer",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4697)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa17-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4699),
                            Name = "Preorder",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4699)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa18-aaaa-aaaa-aaaa-aaaaaaaaaaa8"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4701),
                            Name = "Popular Choice",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4701)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa19-aaaa-aaaa-aaaa-aaaaaaaaaaa9"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4713),
                            Name = "Hot Deal",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4713)
                        },
                        new
                        {
                            Id = new Guid("aaaaaa20-aaaa-aaaa-aaaa-aaaaaaaaaaa0"),
                            CreatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4715),
                            Name = "Back in Stock",
                            UpdatedAt = new DateTime(2025, 9, 10, 18, 40, 37, 60, DateTimeKind.Utc).AddTicks(4716)
                        });
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Order", b =>
                {
                    b.HasOne("MyShop.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MyShop.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShop.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Product", b =>
                {
                    b.HasOne("MyShop.Domain.ListLikeEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.ProductTag", b =>
                {
                    b.HasOne("MyShop.Domain.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyShop.Domain.ListLikeEntities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MyShop.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyShop.Domain.ListLikeEntities.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
